/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  RouterHistory,
} from '@stencil/router';

export namespace Components {
  interface AppHeader {
    'history': RouterHistory;
    'isAuth': boolean;
    'userName': string;
  }
  interface AppHome {}
  interface AppRoot {
    'history': RouterHistory;
  }
  interface FlowManagement {}
  interface OktaLogin {
    'history': RouterHistory;
  }
}

declare global {


  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLFlowManagementElement extends Components.FlowManagement, HTMLStencilElement {}
  var HTMLFlowManagementElement: {
    prototype: HTMLFlowManagementElement;
    new (): HTMLFlowManagementElement;
  };

  interface HTMLOktaLoginElement extends Components.OktaLogin, HTMLStencilElement {}
  var HTMLOktaLoginElement: {
    prototype: HTMLOktaLoginElement;
    new (): HTMLOktaLoginElement;
  };
  interface HTMLElementTagNameMap {
    'app-header': HTMLAppHeaderElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'flow-management': HTMLFlowManagementElement;
    'okta-login': HTMLOktaLoginElement;
  }
}

declare namespace LocalJSX {
  interface AppHeader {
    'history'?: RouterHistory;
    'isAuth'?: boolean;
    'onAuthChange'?: (event: CustomEvent<any>) => void;
    'userName'?: string;
  }
  interface AppHome {}
  interface AppRoot {
    'history'?: RouterHistory;
  }
  interface FlowManagement {}
  interface OktaLogin {
    'history'?: RouterHistory;
    'onAuthChange'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'app-header': AppHeader;
    'app-home': AppHome;
    'app-root': AppRoot;
    'flow-management': FlowManagement;
    'okta-login': OktaLogin;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-header': LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'flow-management': LocalJSX.FlowManagement & JSXBase.HTMLAttributes<HTMLFlowManagementElement>;
      'okta-login': LocalJSX.OktaLogin & JSXBase.HTMLAttributes<HTMLOktaLoginElement>;
    }
  }
}


